rotating_laser:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
  # Velocity Controllers ---------------------------------------
  base_laser_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: base_laser_joint
    pid: {p: 0.001, i: 0.0, d: 0.0}
    